title: "Secrets Detection: Найди утечку"
description: |
  Вам предоставлен доступ к git-репозиторию проекта.
  В истории коммитов разработчики случайно закоммитили секретные данные.
  Используйте инструменты поиска секретов или ручной анализ, чтобы найти флаг.

  Подсказка: секрет мог быть удалён в последующем коммите, но остаётся в истории `git`.
type: ctf
order: 8
config:
  difficulty: low
  tags: [secrets, sast, appsec]
  max_points: 150
  docker_image: lms/secrets-in-code
  container_port: 80
  ttl_minutes: 120
  flag_hash: "c2ab5d1b3ef292f8dfb90c093228b290e51586885927be586c2098acaaa565f5"
