title: "SQL Injection: Практика"
description: |
  Уязвимое веб-приложение с SQL-инъекцией.
  Найдите и проэксплуатируйте уязвимость, чтобы получить флаг.
type: ctf
order: 2
config:
  difficulty: low
  tags: [sqli, web, owasp-top-10]
  max_points: 150
  docker_image: lms/sqli-basic
  container_port: 80
  ttl_minutes: 120
  flag_hash: "5a53d8bcd6173e75dee753b26a05f7ec66dac915b1d52c6b8d9ec2f580a44f79"
